# Generated by Django 2.0.1 on 2018-01-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='borrowing',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.Reader'),
        ),
    ]
